services:
  mongo:
    image: docker.io/library/mongo:latest
    container_name: mongo
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
